name: ⛅ Deploy Workers
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm i
      - run: sed -i s/KV_NAME/${{ secrets.KV_NAME }}/g wrangler.toml
